services:
  postgres:
    image: postgres:alpine3.22
    container_name: simple-bank-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: simple_bank
    ports:
      - "54322:5432"  # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:8-alpine
    container_name: simple-bank-redis
    ports: []

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-bank-api
    ports:
      - "8080:8080"
      - "9090:9090"
    env_file:
      - app.env
    environment:
      DB_SOURCE: postgresql://postgres:root@postgres:5432/simple_bank?sslmode=disable
      MIGRATION_URL: file:///app/db/migration
      REDIS_ADDRESS: redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data:
