services:
  postgres:
    image: postgres:alpine3.22
    container_name: simple-bank-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: simple_bank
    ports:
      - "54322:5432"  # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:8-alpine
    container_name: simple-bank-redis
    ports: []
  rabbitmq:
    image: rabbitmq:4-management
    container_name: simple-bank-rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: simple-bank-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - default
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: simple-bank-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"      # Internal (Docker network)
      - "29092:29092"    # External (localhost)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: |
        PLAINTEXT://simple-bank-kafka:9092,
        PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - default
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: simple-bank-consumer
    environment:
      - KAFKA_BROKERS=simple-bank-kafka:9092 # Single broker (default):
      # Multiple brokers (jika Kafka cluster):
      # - KAFKA_BROKERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - KAFKA_TOPIC=transaction-events
      - KAFKA_GROUP_ID=transaction-consumer-group
      - DATABASE_DSN=postgresql://postgres:root@postgres:5432/simple_bank?sslmode=disable  # for DLQ
      - EMAIL_ENABLED=false
      - ANALYTICS_ENABLED=false
      - PUSH_ENABLED=false
    depends_on:
      - kafka
      - postgres
    networks:
      - default
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-bank-api
    ports:
      - "8080:8080"   # HTTP gateway
      - "9090:9090"   # gRPC
      - "9091:9091"   # Prometheus metrics
    env_file:
      - app.env
    environment:
      DB_SOURCE: postgresql://postgres:root@postgres:5432/simple_bank?sslmode=disable
      MIGRATION_URL: file:///app/db/migration
      REDIS_ADDRESS: redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      kafka:          
        condition: service_healthy
volumes:
  postgres_data:

networks:
  simple-bank:
    driver: bridge
