services:
  postgres:
    image: postgres:alpine3.22
    container_name: simple-bank-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: simple_bank
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-bank-api
    ports:
      - "8080:8080"
      - "9090:9090"
    env_file:
      - app.env
    environment:
      DB_SOURCE: postgresql://postgres:root@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--"]
    command: ["/app/main"]

volumes:
  postgres_data:
