// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dead_letter.sql

package db

import (
	"context"
)

const createDeadLetterEvent = `-- name: CreateDeadLetterEvent :exec
INSERT INTO dead_letter_events (
    original_event_id,
    event_type,
    payload,
    error_message,
    retry_count
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateDeadLetterEventParams struct {
	OriginalEventID int64  `json:"original_event_id"`
	EventType       string `json:"event_type"`
	Payload         []byte `json:"payload"`
	ErrorMessage    string `json:"error_message"`
	RetryCount      int32  `json:"retry_count"`
}

func (q *Queries) CreateDeadLetterEvent(ctx context.Context, arg CreateDeadLetterEventParams) error {
	_, err := q.db.Exec(ctx, createDeadLetterEvent,
		arg.OriginalEventID,
		arg.EventType,
		arg.Payload,
		arg.ErrorMessage,
		arg.RetryCount,
	)
	return err
}

const deleteDeadLetterEvent = `-- name: DeleteDeadLetterEvent :exec
DELETE FROM dead_letter_events
WHERE id = $1
`

func (q *Queries) DeleteDeadLetterEvent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDeadLetterEvent, id)
	return err
}

const listDeadLetterEvents = `-- name: ListDeadLetterEvents :many
SELECT id, original_event_id, event_type, payload, error_message, retry_count, created_at FROM dead_letter_events
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListDeadLetterEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDeadLetterEvents(ctx context.Context, arg ListDeadLetterEventsParams) ([]DeadLetterEvent, error) {
	rows, err := q.db.Query(ctx, listDeadLetterEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeadLetterEvent{}
	for rows.Next() {
		var i DeadLetterEvent
		if err := rows.Scan(
			&i.ID,
			&i.OriginalEventID,
			&i.EventType,
			&i.Payload,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
