// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64              `json:"id"`
	Owner     string             `json:"owner"`
	Balance   int64              `json:"balance"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Events that failed processing and need manual review or retry
type DeadLetterEvent struct {
	ID              int64              `json:"id"`
	AggregateType   string             `json:"aggregate_type"`
	AggregateID     int64              `json:"aggregate_id"`
	EventType       string             `json:"event_type"`
	Payload         []byte             `json:"payload"`
	ErrorMessage    string             `json:"error_message"`
	FailedAt        pgtype.Timestamptz `json:"failed_at"`
	ConsumerGroup   string             `json:"consumer_group"`
	Topic           string             `json:"topic"`
	RetryCount      int32              `json:"retry_count"`
	MaxRetries      int32              `json:"max_retries"`
	NextRetryAt     pgtype.Timestamptz `json:"next_retry_at"`
	ProcessingStage string             `json:"processing_stage"`
	Resolved        bool               `json:"resolved"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// can be negative or positive
	Amount    int64              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OutboxEvent struct {
	ID            int64              `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   int64              `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	Processed     pgtype.Bool        `json:"processed"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	RefreshToken string             `json:"refresh_token"`
	UserAgent    string             `json:"user_agent"`
	ClientIp     string             `json:"client_ip"`
	IsBlocked    bool               `json:"is_blocked"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// must be positive
	Amount    int64              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	Username          string             `json:"username"`
	HashedPassword    string             `json:"hashed_password"`
	FullName          string             `json:"full_name"`
	Email             string             `json:"email"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ID                pgtype.Int8        `json:"id"`
}
