// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (
    aggregate_type,
    aggregate_id,
    event_type,
    payload
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, aggregate_type, aggregate_id, event_type, payload, processed, created_at
`

type CreateOutboxEventParams struct {
	AggregateType string `json:"aggregate_type"`
	AggregateID   int64  `json:"aggregate_id"`
	EventType     string `json:"event_type"`
	Payload       []byte `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Processed,
		&i.CreatedAt,
	)
	return i, err
}

const listUnprocessedOutboxEvents = `-- name: ListUnprocessedOutboxEvents :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, processed, created_at FROM outbox_events
WHERE processed = FALSE
ORDER BY id
LIMIT $1
`

func (q *Queries) ListUnprocessedOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Processed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventProcessed = `-- name: MarkOutboxEventProcessed :exec
UPDATE outbox_events
SET processed = TRUE
WHERE id = $1
`

func (q *Queries) MarkOutboxEventProcessed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxEventProcessed, id)
	return err
}
