name: Deploy to production

on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with: 
        version: 'v1.35.0'
      id: install

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::459181228984:role/github-actions-simple-bank-ecr
        aws-region: ap-southeast-3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Load secrets and save to app.env
      run: |
        aws secretsmanager get-secret-value \
          --secret-id simple_bank \
          --region ap-southeast-3 \
          --query SecretString \
          --output text \
        | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env

    - name: Build and push image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: simple-bank
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t latest.
        docker push -a $REGISTRY/$REPOSITORY

    - name: Deploy image to Amazon EKS
      run: |
        kubectl apply -f eks/aws-auth.yaml
        kubectl apply -f eks/deployment.yaml
        kubectl apply -f eks/service.yaml
        kubectl apply -f eks/issuer.yaml
        kubectl apply -f eks/ingress.yaml
        
